[build]
target="thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
rustflags=[ "-C", "link-arg=-Tmemory.ld"]
# runner = "arm-none-eabi-gdb -q --batch --ex 'target remote localhost:3333' --ex 'load' --ex 'monitor reset halt' --ex 'continue' --ex 'quit'"
runner='probe-rs run --chip STM32F103C8T6'